### ISSUE TITLE
return in while broken

### ISSUE THREAD

**Issue by WebFreak001** [gregtour/duck-lang#22]
this code should actually just output `hello`:

```lua
function foo()
	while(true) do
		return "hello"
	loop
end

duck.println(foo())
```

Because return breaks out of while loops but in here it doesn't. It should return "hello" right at the first iteration but its being stuck there.

**Comment by WebFreak001** [comment]
Update: break in while seems to work just fine

```lua
function foo()
    while(true) do
        break
    loop
    return "hello"
end

duck.println(foo())
```

Maybe add same functionality to return?

**Comment by gregtour** [comment]
Good catch.

**Comment by WebFreak001** [comment]
happened when i was writing an array length function in duck

**Comment by WebFreak001** [comment]
Maybe adding more unittests will prevent this?

**Comment by gregtour** [comment]
Tests would be great. We have a framework for testing, but we don't have any unit tests currently. 

I fixed this issue in the latest revision:
https://github.com/gregtour/duck-lang/commit/6182733936279ec5f7e00709882ea6bce43a4beb

**Comment by gregtour** [comment]
As a heads up, automated unit tests have been added between https://github.com/gregtour/duck-lang/commit/e38d86af562bfd8566b1c98dc0006ddd2d2224ed and https://github.com/gregtour/duck-lang/commit/1c7955b8179fd8f43417ec2959a93dc0038d13ac.

See: https://github.com/gregtour/duck-lang/blob/master/test/testcases.txt

If you find any more bugs or issues please report them and once fixed we will provide tests to prevent regression.

**Comment by WebFreak001** [comment]
I think it would be also useful to have embedded unittests in duck code like this:

```lua
unittest
    a = 5
    b = 4
    assert(a + b == 9, "Invalid integer addition")
end
```

They should be like functions that cant be called manually, but instead get called before everything else when running with a unittest flag or something like that.

**Comment by gregtour** [comment]
That's fine, but it's possible they might not be tested of the interpreter fails.

**Comment by gregtour** [comment]
*if
